// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBR9N7iv5bTWQNsgm6Tg-W7IVPwQCnBXo',
    appId: '1:937470118371:web:3f510c66187f8339e5b8d6',
    messagingSenderId: '937470118371',
    projectId: 'konie-9b808',
    authDomain: 'konie-9b808.firebaseapp.com',
    storageBucket: 'konie-9b808.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJFWbqb3k71AhWnuV76eEHWHWcj9mXwvY',
    appId: '1:937470118371:android:a4a43450a8eba78ce5b8d6',
    messagingSenderId: '937470118371',
    projectId: 'konie-9b808',
    storageBucket: 'konie-9b808.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0beaFN-b0m1iw7k3BghFm3V-f4RH7OmI',
    appId: '1:937470118371:ios:76f2b3f50dd114d6e5b8d6',
    messagingSenderId: '937470118371',
    projectId: 'konie-9b808',
    storageBucket: 'konie-9b808.appspot.com',
    iosClientId: '937470118371-jnaou3us8g6duk7khf93ko826f0hbvid.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyecto',
  );
}
